site_name: 敏捷攀樹手冊
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  extra:
    homepage: https://agile-tree-climbing-manual.readthedocs.io
  language: zh-TW
  nav_style: dark
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
  palette:
    - scheme: default
      toggle:
        name: Switch to dark mode
        icon: material/toggle-switch
      primary: blue
    - scheme: slate
      toggle:
        name: Switch to light mode
        icon: material/toggle-switch-off-outline
      primary: indigo
  features:
    # - navigation.instant # 當點擊其他頁面時網頁不會重新整理且表留只在首頁
    - navigation.tracking
    # - navigation.tabs # 目錄橫放至頂端
    # - navigation.tabs.sticky # 目錄橫放至頂端
    # - navigation.sections # 左側目錄全部攤開
    - navigation.expand # 左側目錄全部攤開但可以收合
    - navigation.top
    # - toc.integrate # 右側目錄加入至左側目錄
    - search.suggest # 建議搜尋功能
    # - navigation.indexes # 只顯示部份索引
    - search.highlight
    - search.share
repo_url: https://github.com/Uesugi-Summer-Sea/Agile-Tree-Climbing-Manual
plugins:
  - search
  - mermaid2
authors: Chenzhi Wu
markdown_extensions:
  - meta
  - smarty
  - mdx_truly_sane_lists
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.arithmatex:
      generic: true
  - markdown_katex:
      no_inline_svg: True
      insert_fonts_css: True
      macro-file: macros.tex

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra:
  analytics:
    provider: google
    property: UA-156555093-1
